name: unifi-protect-backup-viewer

services:
  unifi-protect-backup-viewer:
    image: gitea.internal.egeback.com/egeback/unifi-protect-backup-viewer:dev
    container_name: unifi-protect-backup-viewer
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /mnt/tank/nvr/UniFi:/nvr:ro
      - ./data:/data
      - /dev/dri:/dev/dri
    group_add:
      - "44"  # video
      - "107" # render
    env_file:
      - .env
    environment:
      TZ: Europe/Stockholm
